# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  auto_start_writes:
    description: "Whether to auto start continuous writes on relation events."
    type: boolean
    default: true
  database_name:
    description: "Name of database to direct continuous writes to"
    type: string
    default: "continuous_writes_database"
